version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/data # Mount a named volume for database persistence
    env_file:
      - ./.env

volumes:
  db_data: